version: '3'
services:
  app:
    container_name: work
    restart: always
    build: .
    ports:
      - '80:3000'
    links: 
        - mongo
  api:
        container_name: api
        build: ./movie-app/server
        ports: 
          - '8080:8080'
        depends_on: 
          - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'